server:
  port: ${PORT:8080}

spring:
  application:
    name: tttnBE

  datasource:
    url: jdbc:sqlserver://ticketxDB.mssql.somee.com:1433;databaseName=ticketxDB;encrypt=true;trustServerCertificate=true;
    username: courage123_SQLLogin_1
    password: ctgnf2bcvj
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

    jpa:
      hibernate:
        ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          format_sql: true